import { ID_Screen } from "./enunShortCutService";

export class Permission  {
    code?: ScreenPermission;
    description?: string;
    sons?: SonsPermisssion[]
}

export class SonsPermisssion {
    code?: ID_Permission;
    description?: string;
}


export type ScreenPermission = ID_ScreenPermission | ID_Screen;
export type ID_Permission = 
    ID_PermissionOperation | ID_PermissionShortCut | ID_PermissionModal | ID_PermissionMonitoreo | 
    ID_PermissionMaintenanceDriver | ID_PermissionMaintenanceUser | ID_PermissionMaintenanceCompany | ID_PermissionMaintenanceArea | ID_PermissionMaintenanceCostCenter | ID_PermissionMaintenanceVehicle | ID_PermissionMaintenanceMessage | 
    ID_PermissionPermission | ID_PermissionReports | ID_PermissionMaintenanceZone  | ID_PermissionMaintenanceClient;

export enum ID_ScreenPermission{
    SHORT_CUT = "SHORT_CUT",    
}

export enum ID_PermissionOperation {
    EVENT_NEW_TRIP = "EVENT_NEW_TRIP",
    EVENT_FIND_TYPE = "EVENT_FIND_TYPE",
    EVENT_FIND_STATUS = "EVENT_FIND_STATUS",

    EVENT_OFFER_TRIP = "EVENT_OFFER_TRIP",
    EVENT_CANCEL_TRIP = "EVENT_CANCEL_TRIP",
    EVENT_REMOVER_DRIVER = "EVENT_REMOVER_DRIVER",
    EVENT_ASSING_MOVIL = "EVENT_ASSING_MOVIL",
    EVENT_SHOW_TRACKING = "EVENT_SHOW_TRACKING",
    EVENT_EDIT_TRIP= "EVENT_EDIT_TRIP",
    EVENT_RETAINED_TRIP = "EVENT_RETAINED_TRIP",
    EVENT_DUPLICATE_TRIP = "EVENT_DUPLICATE_TRIP",

    PANEL_MOVIL = "PANEL_MOVIL",

    EVENT_UPDATE_DATA_CONFIDENTIAL = "EVENT_UPDATE_DATA_CONFIDENTIAL",    
    EVENT_UPDATE_HOURS_SERVICE = "EVENT_UPDATE_HOURS_SERVICE",
    EVENT_UPDATE_SERVICE = "EVENT_UPDATE_SERVICE",
    EVENT_UPDATE_TARIFF_COMPANY  = "EVENT_UPDATE_TARIFF_COMPANY",
    EVENT_AUTOMATIC_FIND = "EVENT_AUTOMATIC_FIND",
    EVENT_CHANGE_AUTOMATIC_FIND = "EVENT_CHANGE_AUTOMATIC_FIND"
}

export enum ID_PermissionShortCut {
    SHORTCUT_EVENT_NEW_TRIP = "SHORTCUT_EVENT_NEW_TRIP",
    SHORTCUT_EVENT_EDIT_TRIP = "SHORTCUT_EVENT_EDIT_TRIP",
    SHORTCUT_EVENT_FIND_SCREEN = "SHORTCUT_EVENT_FIND_SCREEN",
    SHORTCUT_EVENT_FIND_MONITORING= "SHORTCUT_EVENT_FIND_MONITORING",
    SHORTCUT_EVENT_TYPE_CAR = "SHORTCUT_EVENT_TYPE_CAR",
    SHORTCUT_EVENT_SEARCH_ID = "SHORTCUT_EVENT_SEARCH_ID",
    SHORTCUT_EVENT_LIST_SERVICE = "SHORTCUT_EVENT_LIST_SERVICE",

    SHORTCUT_EVENT_UPDATE_DATA_CONFIDENTIAL = "SHORTCUT_EVENT_UPDATE_DATA_CONFIDENTIAL",    
    SHORTCUT_EVENT_UPDATE_HOURS_SERVICE = "SHORTCUT_EVENT_UPDATE_HOURS_SERVICE",
    SHORTCUT_EVENT_UPDATE_SERVICE = "SHORTCUT_EVENT_UPDATE_SERVICE",
    SHORTCUT_EVENT_UPDATE_TARIFF_COMPANY  = "SHORTCUT_EVENT_UPDATE_TARIFF_COMPANY",
    SHORTCUT_SMS_INFORMATION_DRIVER  = "SHORTCUT_SMS_INFORMATION_DRIVER",

    SHORTCUT_DRIVER_DETAILS  = "SHORTCUT_DRIVER_DETAILS",
    SHORTCUT_DRIVER_LAST_TRIP = "SHORTCUT_DRIVER_LAST_TRIP",
    SHORTCUT_DRIVER_DATA_LOG = "SHORTCUT_DRIVER_DATA_LOG",
    SHORTCUT_DRIVER_BLOCKED = "SHORTCUT_DRIVER_BLOCKED",
    SHORTCUT_DRIVER_ALL_TRIPS = "SHORTCUT_DRIVER_ALL_TRIPS",
    SHORTCUT_DRIVER_TRACKING = "SHORTCUT_DRIVER_TRACKING",
    SHORTCUT_DRIVER_MESSAGES = "SHORTCUT_DRIVER_MESSAGES",
    SHORTCUT_DRIVER_PRIORITY = "SHORTCUT_DRIVER_PRIORITY",
    SHORTCUT_DRIVER_VIEW_POSITION = "SHORTCUT_DRIVER_VIEW_POSITION",

    SHORTCUT_DISABLED_USER  = "SHORTCUT_DISABLED_USER",
    SHORTCUT_DISABLED_IVR = "SHORTCUT_DISABLED_IVR"
}

export enum ID_PermissionModal {
    EVENT_NEW_CLIENT = "EVENT_NEW_CLIENT",
    EVENT_CHANGE_COVERAGE = "EVENT_CHANGE_COVERAGE",
    EVENT_ADD_PASSENGER = "EVENT_ADD_PASSENGER",
    EVENT_MORE_DETAILS = "EVENT_MORE_DETAILS",
    EVENT_MANAGE_DESTINATION = "EVENT_MANAGE_DESTINATION",
    EVENT_CHANGE_PAYMENT_TYPE = "EVENT_CHANGE_PAYMENT_TYPE",
    EVENT_CANCEL_TRIP_MODAL = "EVENT_CANCEL_TRIP_MODAL",
    EVENT_REMOVER_DRIVER_MODAL = "EVENT_REMOVER_DRIVER_MODAL",
    EVENT_OFFER_TRIP_MODAL = "EVENT_OFFER_TRIP_MODAL",
    EVENT_SAVE_TRIP = "EVENT_SAVE_TRIP",
    EVENT_RETAINED_TRIP_MODAL = "EVENT_RETAINED_TRIP_MODAL",
    EVENT_SHOW_AUDIT = "EVENT_SHOW_AUDIT"
}

export enum ID_PermissionMonitoreo {
    EVENT_FIND_STATUS_DRIVER = "EVENT_FIND_STATUS_DRIVER",
    EVENT_FIND_STATUS_TRIP = "EVENT_FIND_STATUS_TRIP",
    EVENT_FIND_PAYMENT_TYPE = "EVENT_FIND_PAYMENT_TYPE",
    EVENT_FIND_SERVICE_TYPE = "EVENT_FIND_SERVICE_TYPE",
}

export enum ID_PermissionMaintenanceDriver {
    EVENT_NEW_DRIVER = "EVENT_NEW_DRIVER",
    EVENT_EDIT_DRIVER = "EVENT_EDIT_DRIVER",
    EVENT_SEARCH_DRIVER = "EVENT_SEARCH_DRIVER"
}

export enum ID_PermissionMaintenanceCostCenter {
    EVENT_NEW_COSTCENTER = "EVENT_NEW_COSTCENTER",
    EVENT_EDIT_COSTCENTER = "EVENT_EDIT_COSTCENTER",
    EVENT_SEARCH_COSTCENTER = "EVENT_SEARCH_COSTCENTER"
}

export enum ID_PermissionMaintenanceUser {
    EVENT_NEW_USER = "EVENT_NEW_USER",
    EVENT_EDIT_USER = "EVENT_EDIT_USER",
    EVENT_SEARCH_USER = "EVENT_SEARCH_USER"
}
export enum ID_PermissionMaintenanceClient {
    EVENT_NEW_CLIENT = "EVENT_NEW_CLIENT",
    EVENT_EDIT_CLIENT = "EVENT_EDIT_CLIENT",
    EVENT_SEARCH_CLIENT = "EVENT_SEARCH_CLIENT"
}


export enum ID_PermissionMaintenanceCompany {
    EVENT_NEW_COMPANY = "EVENT_NEW_COMPANY",
    EVENT_EDIT_COMPANY = "EVENT_EDIT_COMPANY",
    EVENT_SEARCH_COMPANY = "EVENT_SEARCH_COMPANY"
}

export enum ID_PermissionMaintenanceArea{
    EVENT_NEW_AREA = "EVENT_NEW_AREA",
    EVENT_EDIT_AREA = "EVENT_EDIT_AREA",
    EVENT_SEARCH_AREA = "EVENT_SEARCH_AREA"
}

export enum ID_PermissionMaintenanceZone {
    EVENT_NEW_ZONE= "EVENT_NEW_ZONE",
    EVENT_EDIT_ZONE = "EVENT_EDIT_ZONE",
    EVENT_SEARCH_ZONE = "EVENT_SEARCH_ZONE"
}


export enum ID_PermissionMaintenanceVehicle {
    EVENT_NEW_VEHICLE = "EVENT_NEW_VEHICLE",
    EVENT_EDIT_VEHICLE = "EVENT_EDIT_VEHICLE",
    EVENT_SEARCH_VEHICLE = "EVENT_SEARCH_VEHICLE"
}

export enum ID_PermissionMaintenanceMessage {
    EVENT_SEND_MESSAGE = "EVENT_SEND_MESSAGE",
    EVENT_FIND_CONVERSATION = "EVENT_FIND_CONVERSATION",
    EVENT_FIND_TO_CHAT = "EVENT_FIND_TO_CHAT"
}

export enum ID_PermissionPermission {
    EVENT_PERMISSION_EDIT = "EVENT_PERMISSION_EDIT"
}

export enum ID_PermissionReports {
    EVENT_FIND_REPORTS = "EVENT_FIND_REPORTS"
}